name: Matrix stry

on:
  push

jobs:
    matrix-configration:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker details
        run: docker info
      
    
      - name: Run images
        run: docker run ${{ matrix.images }}  
