name: My first programm

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "My first prct"

        - name: Add permissions
          run : chmod 755 hellowoldr.sh

        - name: list files
          run : ls -ltra

        - name: Execute shell script
          run: ./hellowoldr.sh

        - name: Read file
          run: cat readme.md